### PR TITLE
Fixed the UI Bug in course-finder page's filter dropdowns

### PR DESCRIPTION
**Pull request by AWorldOfMysteries**
Added the _getPopupContainer_  prop with the appropriate value, which is used in the Select component from the Ant Design library. Added the prop to all the three Select components in CourseFinderFilterForm.jsx

Inspired from [https://stackoverflow.com/questions/71206531/ant-design-select-options-not-vanish-on-scroll-it-scrolls-to-other-places-upon](https://stackoverflow.com/questions/71206531/ant-design-select-options-not-vanish-on-scroll-it-scrolls-to-other-places-upon)

**Fixes issue #76**

### CODE REVIEW

**Comment by vk0812** [comment]
Could you add an image of the new design?

**Comment by AWorldOfMysteries** [comment]
Here is the image:

resobin

Now outside scrolling will not displace the filter dropdown container.

**Comment by vk0812** [comment]
I will test it and comment. In the mean time you could also improve the design of the dropdowns (so that they match the ResoBin Theme)

**Comment by AWorldOfMysteries** [comment]
@vk0812 
Please give feedback on this design of the dropdowns.
Also were you able to test my code? Please let me know in case of any issues.

dropdown_theme

**Comment by relaxxpls** [comment]
Is it scroll stable?
Make bg dark, text white, add border radius

**Comment by vk0812** [comment]
Yes the scroll is stable 
@AWorldOfMysteries make the UI changes as mentioned by @relaxxpls 
And then we can merge

**Comment by AWorldOfMysteries** [comment]
Hi @vk0812 !
I have tried to implement the UI changes as mentioned by @relaxxpls
Please verify and let me know.

Also, my attempt to make this contribution is for the DOPE event.

**Comment by vk0812** [comment]
@AWorldOfMysteries I have looked into it please raise a PR to the DOPE branch not the master branch

**Comment by AWorldOfMysteries** [comment]
Okay, cool..

**Pull request closed without merging**
