### PR TITLE
Keymii timetable clashes

### LINKED ISSUE #84: Half sem courses shows slot clashes
Course slot clashing warning don't differentiate between half sem and full sem courses. This is a problem while making freshie timetables because they have a lot of half sem courses. A solution to this could be to relax the slot clash check if there are two half sem courses in the same slot.

image

### LINKED ISSUE #91: Bugs on Timetable page
- [ ]  The PNG download does not work
- [ ]  The page reloads when a new course is added, which is irritating

### PR DESCRIPTION
**Pull request by ayushk26**

### CODE REVIEW

**Comment by ayushk26** [comment]
@Chinoscode111 can you check this branch as I am getting some issues. When you add 2 courses in the same slot, and then after opening the timetable page course search bar doesn't work properly. Ex- when you type something It removes one of the courses from the timetable. And even the search doesn't show any results. These were 2 issues, try testing it more rigrously as there may be more bugs. Let me know if you need any help.

**Comment by ayushk26** [comment]
Timetable slot clashes needs to be fixed in shared timetable as well.

**Comment by Chinoscode111** [comment]
Ok will look into this

**Comment by ayushk26** [comment]
@Chinoscode111 This branch still has some issues, try adding half sem courses from course search bar in the timetable page. It show No timetable found for that course. Try to fix that as well.

**Pull request merged**
